require('dotenv').config();
const express=require('express'),helmet=require('helmet'),rateLimit=require('express-rate-limit'),cookieParser=require('cookie-parser'),jwt=require('jsonwebtoken'),path=require('path');
const {db,save,nextId,hashPassword,safe,now}=require('./db');
const app=express(),PORT=Number(process.env.PORT||4000),SECRET=process.env.JWT_SECRET||'dev-secret-change-me',SECURE=process.env.COOKIE_SECURE==='true';
app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'100kb'}));app.use(cookieParser());app.use(rateLimit({windowMs:15*60*1000,limit:500}));app.use(express.static(path.join(__dirname,'public')));
const authLimiter=rateLimit({windowMs:15*60*1000,limit:15});
const sign=u=>jwt.sign({id:u.id,role:u.role,name:u.name},SECRET,{expiresIn:'4h'});
function setSession(res,u){res.cookie('kc_session',sign(u),{httpOnly:true,sameSite:'lax',secure:SECURE,maxAge:4*60*60*1000});}
function auth(req,res,next){try{const t=req.cookies.kc_session;if(!t)return res.status(401).json({error:'Please sign in.'});req.user=jwt.verify(t,SECRET);next();}catch{res.clearCookie('kc_session');res.status(401).json({error:'Session expired. Please sign in again.'});}}
function officer(req,res,next){if(req.user.role!=='officer')return res.status(403).json({error:'Officer access required.'});next();}
const centerFor=t=>db.centers.find(c=>c.id===t.center_id);
app.get('/api/health',(q,s)=>s.json({ok:true,version:'5.0',service:'KisanConnect'}));
app.post('/api/auth/register',authLimiter,(req,res)=>{const {name,phone,password,language='en'}=req.body||{};if(!name||!/^[0-9]{10}$/.test(phone||'')||!password||password.length<8)return res.status(400).json({error:'Use a name, 10-digit mobile number and password of 8+ characters.'});if(db.users.some(u=>u.phone===phone))return res.status(409).json({error:'Mobile number already registered.'});const u={id:nextId(db.users),name:name.trim(),phone,password_hash:hashPassword(password),role:'farmer',language,created_at:now()};db.users.push(u);save();setSession(res,u);res.json({user:safe(u)});});
app.post('/api/auth/login',authLimiter,(req,res)=>{const {phone,password}=req.body||{};const u=db.users.find(x=>x.phone===phone&&x.password_hash===hashPassword(password||''));if(!u)return res.status(401).json({error:'Invalid mobile number or password.'});setSession(res,u);res.json({user:safe(u)});});
app.post('/api/auth/logout',(q,s)=>{s.clearCookie('kc_session');s.json({ok:true})});app.get('/api/me',auth,(q,s)=>s.json({user:safe(db.users.find(u=>u.id===q.user.id))}));
app.patch('/api/profile/language',auth,(req,res)=>{const lang=['en','te','hi'].includes(req.body.language)?req.body.language:'en';const u=db.users.find(x=>x.id===req.user.id);if(!u)return res.status(404).json({error:'User not found.'});u.language=lang;save();res.json({user:safe(u)});});
app.get('/api/dashboard',auth,(req,res)=>{const mine=db.tokens.filter(t=>t.user_id===req.user.id).sort((a,b)=>b.id-a.id);const active=mine.find(t=>t.status==='Waiting')||null;const center=active&&centerFor(active);const ahead=center?Math.max(0,center.queue-1):0;res.json({active:active?{...active,center_name:center.name,district:center.district,ahead,eta:Math.max(8,ahead*7)}:null,tokenCount:mine.length,completed:mine.filter(t=>t.status==='Completed').length,openCenters:db.centers.filter(c=>c.status==='Open').length,alerts:db.notifications.filter(n=>n.user_id===req.user.id).slice(-10).reverse()});});
app.get('/api/centers',(req,res)=>{let q=String(req.query.q||'').toLowerCase().trim();let crop=String(req.query.crop||'');let rows=db.centers.filter(c=>(!q||c.name.toLowerCase().includes(q)||c.district.toLowerCase().includes(q))&&(!crop||c.crop===crop)).sort((a,b)=>a.queue-b.queue);res.json({centers:rows});});
app.get('/api/market',(req,res)=>res.json({prices:db.prices,live:Boolean(process.env.MARKET_API_URL),updated_at:Math.max(...db.prices.map(p=>new Date(p.updated_at).getTime()))}));
app.post('/api/market/refresh',auth,(req,res)=>{const nowIso=now();db.prices.forEach((p,i)=>{const base=(i%2===0?1:-1)*(0.1+((Date.now()+i*17)%15)/10);p.change=Math.round((Number(p.change||0)+base)*10)/10;p.price=Math.max(0,Math.round(Number(p.price)*(1+base/1000)));p.updated_at=nowIso});save();res.json({prices:db.prices,live:Boolean(process.env.MARKET_API_URL),updated_at:nowIso});});
app.post('/api/tokens',auth,(req,res)=>{const center=db.centers.find(c=>c.id===Number(req.body.centerId));const crop=String(req.body.crop||'');const quantity=Number(req.body.quantity);if(!center)return res.status(404).json({error:'Center not found.'});if(!crop||!quantity||quantity<=0)return res.status(400).json({error:'Enter crop and quantity.'});const t={id:nextId(db.tokens),user_id:req.user.id,center_id:center.id,token_no:`KC-${Date.now().toString().slice(-8)}`,crop,quantity,status:'Waiting',created_at:now()};db.tokens.push(t);center.queue++;db.notifications.push({id:nextId(db.notifications),user_id:req.user.id,title:'Token created',message:`${t.token_no} is active at ${center.name}.`,created_at:now(),read:false});save();res.json({token:{...t,center_name:center.name,district:center.district,ahead:Math.max(0,center.queue-1),eta:Math.max(8,(center.queue-1)*7)}});});
app.get('/api/tokens',auth,(req,res)=>res.json({tokens:db.tokens.filter(t=>t.user_id===req.user.id).sort((a,b)=>b.id-a.id).map(t=>{const c=centerFor(t);return {...t,center_name:c.name,district:c.district,ahead:t.status==='Waiting'?Math.max(0,c.queue-1):0,eta:t.status==='Waiting'?Math.max(8,(c.queue-1)*7):0};})}));
app.post('/api/tokens/refresh',auth,(req,res)=>{const t=[...db.tokens].reverse().find(x=>x.user_id===req.user.id&&x.status==='Waiting');if(!t)return res.json({token:null});const c=centerFor(t);res.json({token:{...t,center_name:c.name,district:c.district,ahead:Math.max(0,c.queue-1),eta:Math.max(8,(c.queue-1)*7),queue:c.queue}});});
app.post('/api/tokens/:id/cancel',auth,(req,res)=>{const t=db.tokens.find(x=>x.id===Number(req.params.id)&&x.user_id===req.user.id);if(!t)return res.status(404).json({error:'Token not found.'});if(t.status!=='Waiting')return res.status(400).json({error:'Only waiting tokens can be cancelled.'});t.status='Cancelled';const c=centerFor(t);c.queue=Math.max(0,c.queue-1);save();res.json({ok:true});});
app.post('/api/posts',auth,(req,res)=>{const text=String(req.body.text||'').trim();if(!text||text.length>500)return res.status(400).json({error:'Post must be 1–500 characters.'});db.posts.push({id:nextId(db.posts),user_id:req.user.id,text,created_at:now()});save();res.json({ok:true});});
app.get('/api/posts',(req,res)=>res.json({posts:[...db.posts].sort((a,b)=>b.id-a.id).slice(0,50).map(p=>({...p,name:db.users.find(u=>u.id===p.user_id)?.name||'Farmer'}))}));
app.get('/api/notifications',auth,(req,res)=>res.json({notifications:db.notifications.filter(n=>n.user_id===req.user.id).sort((a,b)=>b.id-a.id).slice(0,20)}));
app.post('/api/notifications/read',auth,(req,res)=>{db.notifications.filter(n=>n.user_id===req.user.id).forEach(n=>n.read=true);save();res.json({ok:true})});
app.get('/api/admin/summary',auth,officer,(req,res)=>{res.json({farmers:db.users.filter(u=>u.role==='farmer').length,totalTokens:db.tokens.length,waiting:db.tokens.filter(t=>t.status==='Waiting').length,completed:db.tokens.filter(t=>t.status==='Completed').length,cancelled:db.tokens.filter(t=>t.status==='Cancelled').length,centers:db.centers,prices:db.prices});});
app.patch('/api/admin/centers/:id',auth,officer,(req,res)=>{const c=db.centers.find(x=>x.id===Number(req.params.id));if(!c)return res.status(404).json({error:'Center not found.'});if(req.body.queue!==undefined)c.queue=Math.max(0,Number(req.body.queue)||0);if(req.body.status)c.status=req.body.status;save();res.json({center:c});});
app.patch('/api/admin/tokens/:id',auth,officer,(req,res)=>{const t=db.tokens.find(x=>x.id===Number(req.params.id));if(!t)return res.status(404).json({error:'Token not found.'});const old=t.status;t.status=req.body.status||t.status;if(old==='Waiting'&&t.status!=='Waiting'){const c=centerFor(t);c.queue=Math.max(0,c.queue-1);}if(old!=='Waiting'&&t.status==='Waiting'){centerFor(t).queue++;}db.notifications.push({id:nextId(db.notifications),user_id:t.user_id,title:'Procurement update',message:`Token ${t.token_no} is now ${t.status}.`,created_at:now(),read:false});save();res.json({token:t});});
app.patch('/api/admin/prices/:id',auth,officer,(req,res)=>{const p=db.prices.find(x=>x.id===Number(req.params.id));if(!p)return res.status(404).json({error:'Price record not found.'});const price=Number(req.body.price);if(!price||price<0)return res.status(400).json({error:'Enter a valid price.'});p.price=price;p.change=Number(req.body.change)||0;p.updated_at=now();save();res.json({price:p});});
app.get('/api/admin/tokens',auth,officer,(req,res)=>res.json({tokens:[...db.tokens].sort((a,b)=>b.id-a.id).slice(0,100).map(t=>({...t,farmer:db.users.find(u=>u.id===t.user_id)?.name||'Farmer',center_name:centerFor(t)?.name||'Center'}))}));
app.get('/api/weather',async(req,res)=>{try{const lat=Number(req.query.lat),lon=Number(req.query.lon);if(!Number.isFinite(lat)||!Number.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)throw new Error('Invalid coordinates');const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,weather_code,wind_speed_10m&timezone=auto`);if(!r.ok)throw new Error();const d=await r.json();res.json({live:true,location:{lat,lon,timezone:d.timezone},current:d.current});}catch{res.json({live:false,location:null,current:{temperature_2m:29,relative_humidity_2m:62,wind_speed_10m:11,weather_code:1}})}});
app.post('/api/assistant',auth,(req,res)=>{const m=String(req.body.message||'').toLowerCase();const lang=['en','te','hi'].includes(req.body.language)?req.body.language:'en';const active=[...db.tokens].reverse().find(t=>t.user_id===req.user.id&&t.status==='Waiting');const c=active&&centerFor(active);let reply={en:'I can help with digital tokens, live queue, procurement centers, crop prices, weather and farmer guidance.',te:'నేను డిజిటల్ టోకెన్లు, లైవ్ క్యూ, కొనుగోలు కేంద్రాలు, పంట ధరలు, వాతావరణం మరియు రైతు మార్గదర్శకంలో సహాయం చేయగలను.',hi:'मैं डिजिटल टोकन, लाइव कतार, खरीद केंद्र, फसल कीमत, मौसम और किसान मार्गदर्शन में मदद कर सकता हूं।'}[lang];if(/token|टोकन|టోకెన్/.test(m))reply=active?({en:`Your active token is ${active.token_no} at ${c.name}.`,te:`మీ యాక్టివ్ టోకెన్ ${active.token_no}. కేంద్రం: ${c.name}.`,hi:`आपका सक्रिय टोकन ${active.token_no} है। केंद्र: ${c.name}.`}[lang]):({en:'You do not have an active token. Open Procurement to create one.',te:'మీకు యాక్టివ్ టోకెన్ లేదు. టోకెన్ సృష్టించడానికి కొనుగోలు విభాగాన్ని తెరవండి.',hi:'आपके पास सक्रिय टोकन नहीं है। टोकन बनाने के लिए खरीद खोलें।'}[lang]);else if(/queue|wait|क्यू|कतार|క్యూ/.test(m))reply=active?({en:`There are about ${Math.max(0,c.queue-1)} people ahead. Estimated wait is about ${Math.max(8,(c.queue-1)*7)} minutes.`,te:`మీ ముందు సుమారు ${Math.max(0,c.queue-1)} మంది ఉన్నారు. అంచనా వేచి సమయం ${Math.max(8,(c.queue-1)*7)} నిమిషాలు.`,hi:`आपसे लगभग ${Math.max(0,c.queue-1)} लोग आगे हैं। अनुमानित प्रतीक्षा ${Math.max(8,(c.queue-1)*7)} मिनट है।`}[lang]):({en:'Create a token first to track your queue.',te:'మీ క్యూ ట్రాక్ చేయడానికి ముందుగా టోకెన్ సృష్టించండి.',hi:'अपनी कतार ट्रैक करने के लिए पहले टोकन बनाएं।'}[lang]);else if(/price|rate|भाव|कीमत|ధర/.test(m))reply={en:'Open Market Prices for crop-wise reference prices and the latest feed update.',te:'పంటల వారీ సూచనాత్మక ధరలు మరియు తాజా ఫీడ్ అప్‌డేట్ కోసం మార్కెట్ ధరలను తెరవండి.',hi:'फसल-वार संदर्भ कीमत और नवीनतम फीड अपडेट के लिए बाजार भाव खोलें।'}[lang];else if(/weather|rain|मौसम|वातावरण|వాతావరణ/.test(m))reply={en:'Open Weather & Alerts to use your current browser location for the latest available weather.',te:'మీ ప్రస్తుత బ్రౌజర్ స్థానాన్ని ఉపయోగించి తాజా వాతావరణం కోసం వాతావరణం & హెచ్చరికలను తెరవండి.',hi:'अपने वर्तमान ब्राउज़र स्थान के नवीनतम मौसम के लिए मौसम और अलर्ट खोलें।'}[lang];else if(/security|secure|सुरक्षा|భద్రత/.test(m))reply={en:'Your session uses server-side authentication, an HttpOnly cookie, rate limiting, security headers and role-based officer routes.',te:'మీ సెషన్ సర్వర్ ధృవీకరణ, HttpOnly కుకీ, రేట్ లిమిటింగ్, సెక్యూరిటీ హెడర్లు మరియు ఆఫీసర్ రోల్స్‌తో రక్షించబడింది.',hi:'आपका सत्र सर्वर प्रमाणीकरण, HttpOnly कुकी, रेट लिमिटिंग, सुरक्षा हेडर और अधिकारी भूमिकाओं से सुरक्षित है।'}[lang];res.json({reply});});
app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,()=>console.log(`KisanConnect running at http://localhost:${PORT}`));
